spring:
  application:
    name: Fit Track

  datasource:
    url: jdbc:h2:file:./LOCAL_DATA/h2/app;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password: changeme
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # dev only
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format_sql: true

app:
  jwt:
    secret: "c2VjcmV0c2VjcmV0c2VjcmV0c2VjcmV0MTIzNCE="  # base64 της λέξης "secretsecretsecret1234!"
    issuer: "fittrack"
    audience: "fittrack-users"
    ttl-minutes: 1440
